// <auto-generated />
using System;
using Contacts.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Contacts.DAL.Migrations
{
    [DbContext(typeof(ContextDB))]
    partial class ContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Contacts.DomainModel.Persons.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("NikName");

                    b.HasKey("Id");

                    b.ToTable("people");
                });

            modelBuilder.Entity("Contacts.DomainModel.PhBook.PhoneBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("PersonId");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("TypeNumber");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("phoneBooks");
                });

            modelBuilder.Entity("Contacts.DomainModel.PhBook.PhoneBook", b =>
                {
                    b.HasOne("Contacts.DomainModel.Persons.Person", "person")
                        .WithMany("phoneBooks")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
